/*
 * IDENTIFICATION:
 * stub generated Sun May  9 00:49:07 2021
 * with a MiG generated by bootstrap_cmds-117
 * OPTIONS: 
 */

/* Module kernrw_daemon */

#define	__MIG_check__Request__kernrw_daemon_subsystem__ 1

#include "krw_daemonServer.h"

#ifndef	mig_internal
#define	mig_internal	static __inline__
#endif	/* mig_internal */

#ifndef	mig_external
#define mig_external
#endif	/* mig_external */

#if	!defined(__MigTypeCheck) && defined(TypeCheck)
#define	__MigTypeCheck		TypeCheck	/* Legacy setting */
#endif	/* !defined(__MigTypeCheck) */

#if	!defined(__MigKernelSpecificCode) && defined(_MIG_KERNEL_SPECIFIC_CODE_)
#define	__MigKernelSpecificCode	_MIG_KERNEL_SPECIFIC_CODE_	/* Legacy setting */
#endif	/* !defined(__MigKernelSpecificCode) */

#ifndef	LimitCheck
#define	LimitCheck 0
#endif	/* LimitCheck */

#ifndef	min
#define	min(a,b)  ( ((a) < (b))? (a): (b) )
#endif	/* min */

#if !defined(_WALIGN_)
#define _WALIGN_(x) (((x) + 3) & ~3)
#endif /* !defined(_WALIGN_) */

#if !defined(_WALIGNSZ_)
#define _WALIGNSZ_(x) _WALIGN_(sizeof(x))
#endif /* !defined(_WALIGNSZ_) */

#ifndef	UseStaticTemplates
#define	UseStaticTemplates	0
#endif	/* UseStaticTemplates */

#ifndef MIG_SERVER_ROUTINE
#define MIG_SERVER_ROUTINE
#endif

#ifndef	__DeclareRcvRpc
#define	__DeclareRcvRpc(_NUM_, _NAME_)
#endif	/* __DeclareRcvRpc */

#ifndef	__BeforeRcvRpc
#define	__BeforeRcvRpc(_NUM_, _NAME_)
#endif	/* __BeforeRcvRpc */

#ifndef	__AfterRcvRpc
#define	__AfterRcvRpc(_NUM_, _NAME_)
#endif	/* __AfterRcvRpc */

#ifndef	__DeclareRcvSimple
#define	__DeclareRcvSimple(_NUM_, _NAME_)
#endif	/* __DeclareRcvSimple */

#ifndef	__BeforeRcvSimple
#define	__BeforeRcvSimple(_NUM_, _NAME_)
#endif	/* __BeforeRcvSimple */

#ifndef	__AfterRcvSimple
#define	__AfterRcvSimple(_NUM_, _NAME_)
#endif	/* __AfterRcvSimple */

#define novalue void

#define msgh_request_port	msgh_local_port
#define MACH_MSGH_BITS_REQUEST(bits)	MACH_MSGH_BITS_LOCAL(bits)
#define msgh_reply_port		msgh_remote_port
#define MACH_MSGH_BITS_REPLY(bits)	MACH_MSGH_BITS_REMOTE(bits)

#define MIG_RETURN_ERROR(X, code)	{\
				((mig_reply_error_t *)X)->RetCode = code;\
				((mig_reply_error_t *)X)->NDR = NDR_record;\
				return;\
				}

/* Forward Declarations */


mig_internal novalue _Xread32
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xread64
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xwrite32
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _Xwrite64
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XkernelBase
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XkernelProc
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XallProc
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);

mig_internal novalue _XtaskSelfAddr
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP);


#if ( __MigTypeCheck )
#if __MIG_check__Request__kernrw_daemon_subsystem__
#if !defined(__MIG_check__Request__read32_t__defined)
#define __MIG_check__Request__read32_t__defined

mig_internal kern_return_t __MIG_check__Request__read32_t(__attribute__((__unused__)) __Request__read32_t *In0P)
{

	typedef __Request__read32_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__read32_t__defined) */
#endif /* __MIG_check__Request__kernrw_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine read32 */
mig_internal novalue _Xread32
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint64_t kaddr;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__read32_t __Request;
	typedef __Reply__read32_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__read32_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__read32_t__defined */

	__DeclareRcvRpc(600, "read32")
	__BeforeRcvRpc(600, "read32")

#if	defined(__MIG_check__Request__read32_t__defined)
	check_result = __MIG_check__Request__read32_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__read32_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = krw_read32(In0P->Head.msgh_request_port, In0P->kaddr, &OutP->val, TrailerP->msgh_audit);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(600, "read32")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__kernrw_daemon_subsystem__
#if !defined(__MIG_check__Request__read64_t__defined)
#define __MIG_check__Request__read64_t__defined

mig_internal kern_return_t __MIG_check__Request__read64_t(__attribute__((__unused__)) __Request__read64_t *In0P)
{

	typedef __Request__read64_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__read64_t__defined) */
#endif /* __MIG_check__Request__kernrw_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine read64 */
mig_internal novalue _Xread64
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint64_t kaddr;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__read64_t __Request;
	typedef __Reply__read64_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__read64_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__read64_t__defined */

	__DeclareRcvRpc(601, "read64")
	__BeforeRcvRpc(601, "read64")

#if	defined(__MIG_check__Request__read64_t__defined)
	check_result = __MIG_check__Request__read64_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__read64_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = krw_read64(In0P->Head.msgh_request_port, In0P->kaddr, &OutP->val, TrailerP->msgh_audit);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(601, "read64")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__kernrw_daemon_subsystem__
#if !defined(__MIG_check__Request__write32_t__defined)
#define __MIG_check__Request__write32_t__defined

mig_internal kern_return_t __MIG_check__Request__write32_t(__attribute__((__unused__)) __Request__write32_t *In0P)
{

	typedef __Request__write32_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__write32_t__defined) */
#endif /* __MIG_check__Request__kernrw_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine write32 */
mig_internal novalue _Xwrite32
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint64_t kaddr;
		uint32_t val;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__write32_t __Request;
	typedef __Reply__write32_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__write32_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__write32_t__defined */

	__DeclareRcvRpc(602, "write32")
	__BeforeRcvRpc(602, "write32")

#if	defined(__MIG_check__Request__write32_t__defined)
	check_result = __MIG_check__Request__write32_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__write32_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = krw_write32(In0P->Head.msgh_request_port, In0P->kaddr, In0P->val, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(602, "write32")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__kernrw_daemon_subsystem__
#if !defined(__MIG_check__Request__write64_t__defined)
#define __MIG_check__Request__write64_t__defined

mig_internal kern_return_t __MIG_check__Request__write64_t(__attribute__((__unused__)) __Request__write64_t *In0P)
{

	typedef __Request__write64_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__write64_t__defined) */
#endif /* __MIG_check__Request__kernrw_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine write64 */
mig_internal novalue _Xwrite64
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		NDR_record_t NDR;
		uint64_t kaddr;
		uint64_t val;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__write64_t __Request;
	typedef __Reply__write64_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__write64_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__write64_t__defined */

	__DeclareRcvRpc(603, "write64")
	__BeforeRcvRpc(603, "write64")

#if	defined(__MIG_check__Request__write64_t__defined)
	check_result = __MIG_check__Request__write64_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__write64_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = krw_write64(In0P->Head.msgh_request_port, In0P->kaddr, In0P->val, TrailerP->msgh_audit);

	OutP->NDR = NDR_record;


	__AfterRcvRpc(603, "write64")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__kernrw_daemon_subsystem__
#if !defined(__MIG_check__Request__kernelBase_t__defined)
#define __MIG_check__Request__kernelBase_t__defined

mig_internal kern_return_t __MIG_check__Request__kernelBase_t(__attribute__((__unused__)) __Request__kernelBase_t *In0P)
{

	typedef __Request__kernelBase_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__kernelBase_t__defined) */
#endif /* __MIG_check__Request__kernrw_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine kernelBase */
mig_internal novalue _XkernelBase
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__kernelBase_t __Request;
	typedef __Reply__kernelBase_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__kernelBase_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__kernelBase_t__defined */

	__DeclareRcvRpc(604, "kernelBase")
	__BeforeRcvRpc(604, "kernelBase")

#if	defined(__MIG_check__Request__kernelBase_t__defined)
	check_result = __MIG_check__Request__kernelBase_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__kernelBase_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = krw_kernelBase(In0P->Head.msgh_request_port, &OutP->val, TrailerP->msgh_audit);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(604, "kernelBase")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__kernrw_daemon_subsystem__
#if !defined(__MIG_check__Request__kernelProc_t__defined)
#define __MIG_check__Request__kernelProc_t__defined

mig_internal kern_return_t __MIG_check__Request__kernelProc_t(__attribute__((__unused__)) __Request__kernelProc_t *In0P)
{

	typedef __Request__kernelProc_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__kernelProc_t__defined) */
#endif /* __MIG_check__Request__kernrw_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine kernelProc */
mig_internal novalue _XkernelProc
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__kernelProc_t __Request;
	typedef __Reply__kernelProc_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__kernelProc_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__kernelProc_t__defined */

	__DeclareRcvRpc(605, "kernelProc")
	__BeforeRcvRpc(605, "kernelProc")

#if	defined(__MIG_check__Request__kernelProc_t__defined)
	check_result = __MIG_check__Request__kernelProc_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__kernelProc_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = krw_kernelProc(In0P->Head.msgh_request_port, &OutP->val, TrailerP->msgh_audit);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(605, "kernelProc")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__kernrw_daemon_subsystem__
#if !defined(__MIG_check__Request__allProc_t__defined)
#define __MIG_check__Request__allProc_t__defined

mig_internal kern_return_t __MIG_check__Request__allProc_t(__attribute__((__unused__)) __Request__allProc_t *In0P)
{

	typedef __Request__allProc_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__allProc_t__defined) */
#endif /* __MIG_check__Request__kernrw_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine allProc */
mig_internal novalue _XallProc
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__allProc_t __Request;
	typedef __Reply__allProc_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__allProc_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__allProc_t__defined */

	__DeclareRcvRpc(606, "allProc")
	__BeforeRcvRpc(606, "allProc")

#if	defined(__MIG_check__Request__allProc_t__defined)
	check_result = __MIG_check__Request__allProc_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__allProc_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = krw_allProc(In0P->Head.msgh_request_port, &OutP->val, TrailerP->msgh_audit);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(606, "allProc")
}

#if ( __MigTypeCheck )
#if __MIG_check__Request__kernrw_daemon_subsystem__
#if !defined(__MIG_check__Request__taskSelfAddr_t__defined)
#define __MIG_check__Request__taskSelfAddr_t__defined

mig_internal kern_return_t __MIG_check__Request__taskSelfAddr_t(__attribute__((__unused__)) __Request__taskSelfAddr_t *In0P)
{

	typedef __Request__taskSelfAddr_t __Request;
#if	__MigTypeCheck
	if ((In0P->Head.msgh_bits & MACH_MSGH_BITS_COMPLEX) ||
	    (In0P->Head.msgh_size != (mach_msg_size_t)sizeof(__Request)))
		return MIG_BAD_ARGUMENTS;
#endif	/* __MigTypeCheck */

	return MACH_MSG_SUCCESS;
}
#endif /* !defined(__MIG_check__Request__taskSelfAddr_t__defined) */
#endif /* __MIG_check__Request__kernrw_daemon_subsystem__ */
#endif /* ( __MigTypeCheck ) */


/* Routine taskSelfAddr */
mig_internal novalue _XtaskSelfAddr
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{

#ifdef  __MigPackStructs
#pragma pack(push, 4)
#endif
	typedef struct {
		mach_msg_header_t Head;
		mach_msg_max_trailer_t trailer;
	} Request __attribute__((unused));
#ifdef  __MigPackStructs
#pragma pack(pop)
#endif
	typedef __Request__taskSelfAddr_t __Request;
	typedef __Reply__taskSelfAddr_t Reply __attribute__((unused));

	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	Request *In0P = (Request *) InHeadP;
	Reply *OutP = (Reply *) OutHeadP;
	mach_msg_max_trailer_t *TrailerP;
#if	__MigTypeCheck
	unsigned int trailer_size __attribute__((unused));
#endif	/* __MigTypeCheck */
#ifdef	__MIG_check__Request__taskSelfAddr_t__defined
	kern_return_t check_result;
#endif	/* __MIG_check__Request__taskSelfAddr_t__defined */

	__DeclareRcvRpc(607, "taskSelfAddr")
	__BeforeRcvRpc(607, "taskSelfAddr")

#if	defined(__MIG_check__Request__taskSelfAddr_t__defined)
	check_result = __MIG_check__Request__taskSelfAddr_t((__Request *)In0P);
	if (check_result != MACH_MSG_SUCCESS)
		{ MIG_RETURN_ERROR(OutP, check_result); }
#endif	/* defined(__MIG_check__Request__taskSelfAddr_t__defined) */

	TrailerP = (mach_msg_max_trailer_t *)((vm_offset_t)In0P +
		round_msg(In0P->Head.msgh_size));
	if (TrailerP->msgh_trailer_type != MACH_MSG_TRAILER_FORMAT_0)
		{ MIG_RETURN_ERROR(In0P, MIG_TRAILER_ERROR); }
#if	__MigTypeCheck
	trailer_size = TrailerP->msgh_trailer_size -
		(mach_msg_size_t)(sizeof(mach_msg_trailer_type_t) - sizeof(mach_msg_trailer_size_t));
#endif	/* __MigTypeCheck */
#if	__MigTypeCheck
	if (trailer_size < (mach_msg_size_t)sizeof(audit_token_t))
		{ MIG_RETURN_ERROR(OutP, MIG_TRAILER_ERROR); }
	trailer_size -= (mach_msg_size_t)sizeof(audit_token_t);
#endif	/* __MigTypeCheck */
	OutP->RetCode = krw_taskSelfAddr(In0P->Head.msgh_request_port, &OutP->val, TrailerP->msgh_audit);
	if (OutP->RetCode != KERN_SUCCESS) {
		MIG_RETURN_ERROR(OutP, OutP->RetCode);
	}

	OutP->NDR = NDR_record;


	OutP->Head.msgh_size = (mach_msg_size_t)(sizeof(Reply));
	__AfterRcvRpc(607, "taskSelfAddr")
}



/* Description of this subsystem, for use in direct RPC */
const struct krw_kernrw_daemon_subsystem krw_kernrw_daemon_subsystem = {
	kernrw_daemon_server_routine,
	600,
	608,
	(mach_msg_size_t)sizeof(union __ReplyUnion__krw_kernrw_daemon_subsystem),
	(vm_address_t)0,
	{
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xread32, 12, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__read32_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xread64, 12, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__read64_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xwrite32, 12, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__write32_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _Xwrite64, 13, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__write64_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XkernelBase, 10, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__kernelBase_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XkernelProc, 10, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__kernelProc_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XallProc, 10, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__allProc_t)},
          { (mig_impl_routine_t) 0,
          (mig_stub_routine_t) _XtaskSelfAddr, 10, 0, (routine_arg_descriptor_t)0, (mach_msg_size_t)sizeof(__Reply__taskSelfAddr_t)},
	}
};

mig_external boolean_t kernrw_daemon_server
	(mach_msg_header_t *InHeadP, mach_msg_header_t *OutHeadP)
{
	/*
	 * typedef struct {
	 * 	mach_msg_header_t Head;
	 * 	NDR_record_t NDR;
	 * 	kern_return_t RetCode;
	 * } mig_reply_error_t;
	 */

	mig_routine_t routine;

	OutHeadP->msgh_bits = MACH_MSGH_BITS(MACH_MSGH_BITS_REPLY(InHeadP->msgh_bits), 0);
	OutHeadP->msgh_remote_port = InHeadP->msgh_reply_port;
	/* Minimal size: routine() will update it if different */
	OutHeadP->msgh_size = (mach_msg_size_t)sizeof(mig_reply_error_t);
	OutHeadP->msgh_local_port = MACH_PORT_NULL;
	OutHeadP->msgh_id = InHeadP->msgh_id + 100;
	OutHeadP->msgh_reserved = 0;

	if ((InHeadP->msgh_id > 607) || (InHeadP->msgh_id < 600) ||
	    ((routine = krw_kernrw_daemon_subsystem.routine[InHeadP->msgh_id - 600].stub_routine) == 0)) {
		((mig_reply_error_t *)OutHeadP)->NDR = NDR_record;
		((mig_reply_error_t *)OutHeadP)->RetCode = MIG_BAD_ID;
		return FALSE;
	}
	(*routine) (InHeadP, OutHeadP);
	return TRUE;
}

mig_external mig_routine_t kernrw_daemon_server_routine
	(mach_msg_header_t *InHeadP)
{
	int msgh_id;

	msgh_id = InHeadP->msgh_id - 600;

	if ((msgh_id > 7) || (msgh_id < 0))
		return 0;

	return krw_kernrw_daemon_subsystem.routine[msgh_id].stub_routine;
}
